-- 코드를 작성해주세요
SELECT ED.ID, IFNULL(CC.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) AS CNT
    FROM ECOLI_DATA
    # WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) CC on CC.PARENT_ID = ED.ID
ORDER BY ED.ID