-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS SQ on SQ.FOOD_TYPE = R.FOOD_TYPE AND SQ.MAX_FAV = R.FAVORITES
ORDER BY R.FOOD_TYPE DESC