-- 코드를 작성해주세요
With SIZE_ORDER AS (
    SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN
    FROM ECOLI_DATA
    # ORDER BY SIZE_OF_COLONY DESC
),
CNT AS (
    SELECT COUNT(*) AS E_CNT FROM ECOLI_DATA
)
SELECT ID, 
    CASE
        WHEN RN / C.E_CNT <= 0.25 THEN 'CRITICAL'
        WHEN RN / C.E_CNT <= 0.5 THEN 'HIGH'
        WHEN RN / C.E_CNT <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END
    AS COLONY_NAME
FROM SIZE_ORDER
JOIN CNT C
ORDER BY ID