-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O
JOIN (
    SELECT SEX_UPON_INTAKE, ANIMAL_ID
    FROM ANIMAL_INS
) I on I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME != I.SEX_UPON_INTAKE
ORDER BY O.ANIMAL_ID