-- 코드를 입력하세요
# SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
With PF AS (
    SELECT PLAN_ID,
    CAST(DURATION_TYPE AS SIGNED) AS DURATION_TYPE,
    CAST(DISCOUNT_RATE AS SIGNED) AS DISCOUNT_RATE,
    RANK() OVER (PARTITION BY CAR_TYPE ORDER BY CAST(DURATION_TYPE AS SIGNED)) AS RN
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
    ORDER BY DURATION_TYPE
),
CT AS (
    SELECT CAR_ID, DAILY_FEE, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR
    # WHERE CAR_TYPE = '트럭'
)

SELECT H.HISTORY_ID, 
    ROUND(CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 90
            THEN C.DAILY_FEE - C.DAILY_FEE * (SELECT DISCOUNT_RATE from PF where DURATION_TYPE = 90)/100
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 30
            THEN C.DAILY_FEE - C.DAILY_FEE * (SELECT DISCOUNT_RATE from PF where DURATION_TYPE = 30)/100
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 7
            THEN C.DAILY_FEE - C.DAILY_FEE * (SELECT DISCOUNT_RATE from PF where DURATION_TYPE = 7)/100
        ELSE C.DAILY_FEE
    END) * (DATEDIFF(H.END_DATE, H.START_DATE)+1)
    AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CT C on C.CAR_ID = H.CAR_ID
# LEFT JOIN PF P
# GROUP BY H.HISTORY_ID
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC
