-- 코드를 입력하세요
# SELECT * FROM ANIMAL_OUTS
With RECURSIVE Hours AS (
    SELECT 0 AS `HOUR`, 0 AS `COUNT`
    UNION ALL
    SELECT `HOUR` + 1, 0 AS `COUNT`
    FROM Hours
    WHERE `HOUR` < 23
)

# SELECT * FROM Hours

SELECT `HOUR`, COUNT(ANIMAL_ID) AS `COUNT`
FROM ANIMAL_OUTS O
RIGHT JOIN Hours H on H.HOUR = HOUR(O.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR
