With RECURSIVE Hours AS (
    SELECT 0 AS `HOUR`
    UNION ALL
    SELECT `HOUR` + 1
    FROM Hours
    WHERE `HOUR` < 23
)

SELECT `HOUR`, COUNT(ANIMAL_ID) AS `COUNT`
FROM ANIMAL_OUTS O
RIGHT JOIN Hours H on H.HOUR = HOUR(O.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR