-- 코드를 작성해주세요
With FS AS (
    SELECT `CODE`
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (
    SELECT 1
    FROM FS
    WHERE D.SKILL_CODE & `CODE`
)
ORDER BY D.ID
