-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(
    CASE
        WHEN B.STATUS = 'SALE' THEN 0
        WHEN B.STATUS = 'DONE' THEN B.PRICE
    END
) AS TOTAL_SALES
FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD B on U.USER_ID = B.WRITER_ID
GROUP BY U.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES