-- 코드를 입력하세요
# SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
# FROM MEMBER_PROFILE M
# # JOIN REST_REVIEW R on R.MEMBER_ID = M.MEMBER_ID
# JOIN (
#     SELECT REVIEW_TEXT, REVIEW_DATE, COUNT(REVIEW_ID) OVER(PARTITION BY MEMBER_ID) AS REVIEW_CNT
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
#     ORDER BY REVIEW_CNT DESC
#     LIMIT 1
# ) AS R
# ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT

    # SELECT MEMBER_ID REVIEW_TEXT, REVIEW_DATE, COUNT(*) OVER(PARTITION BY MEMBER_ID) AS REVIEW_CNT
    # FROM REST_REVIEW
    # GROUP BY MEMBER_ID
    # ORDER BY REVIEW_CNT DESC
    # LIMIT 1
    
WITH MAX_REVIEW AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_CNT
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
),
MAX_COUNT AS (
    -- 2단계: 전체 회원 중에서 가장 많은 리뷰 개수(MAX_CNT)를 찾음
    SELECT 
        MAX(REVIEW_CNT) AS MAX_CNT
    FROM 
        MAX_REVIEW
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MAX_REVIEW MR on MR.MEMBER_ID = R.MEMBER_ID
JOIN MAX_COUNT MC ON MR.REVIEW_CNT = MC.MAX_CNT
JOIN MEMBER_PROFILE M on M.MEMBER_ID = MR.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT

# GROUP BY R.MEMBER_ID
# HAVING MAX(MR.REVIEW_CNT) = MR.REVIEW_CNT

# SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE, R.REVIEW_CNT
# FROM MEMBER_PROFILE M
# JOIN (
#     SELECT COUNT(*) AS REVIEW_CNT
#     FROM REST_REVIEW 
#     GROUP BY MEMBER_ID
#     ORDER BY REVIEW_CNT DESC
# ) R on M.MEMBER_ID = R.MEMBER_ID
# WHERE MAX(R.REVIEW_CNT)
