-- 코드를 작성해주세요
SELECT E.ID, E.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E
JOIN (
    SELECT ID, GENOTYPE
    FROM ECOLI_DATA
) P on P.ID = E.PARENT_ID
WHERE E.GENOTYPE & P.GENOTYPE = P.GENOTYPE
ORDER BY E.ID

/*
ID  PID G       PG
2   1   1       1
3   1   3(11)   1(01)
4   2   2(10)   1(01)
5
6   3   5(101)  3(011)

*/