-- 코드를 작성해주세요
SELECT SUM(EG.SCORE) AS SCORE, EG.EMP_NO, EG.EMP_NAME, EG.POSITION, EG.EMAIL
FROM HR_DEPARTMENT D
JOIN (
    SELECT E.EMP_NO, E.EMP_NAME, E.DEPT_ID, E.POSITION, E.EMAIL, G.SCORE FROM HR_EMPLOYEES E
    JOIN HR_GRADE G on G.EMP_NO = E.EMP_NO
    )
AS EG on D.DEPT_ID = EG.DEPT_ID
GROUP BY EG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1