-- 코드를 입력하세요
SELECT
    F.CATEGORY,
    MAX(PRICE) AS MAX_PRICE,
    F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
 SELECT
    PRODUCT_ID,
    RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS C_RN
    FROM FOOD_PRODUCT
) RT on RT.PRODUCT_ID = F.PRODUCT_ID
WHERE RT.C_RN = 1
AND (F.CATEGORY LIKE '과자' or F.CATEGORY LIKE '국' or F.CATEGORY LIKE '김치' or F.CATEGORY LIKE '식용유')
GROUP BY F.CATEGORY
ORDER BY F.PRICE DESC